version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    networks:
      - alzheimer-bot-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - API_URL=http://backend:8000  # Override API_URL to point to backend service
    volumes:
      - ./frontend:/app
      - frontend_data:/app/data
    networks:
      - alzheimer-bot-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  alzheimer-bot-network:
    driver: bridge

volumes:
  backend_data:
  frontend_data: